name: "CI"
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test
        run: bats test/
